views:
  - type: sections
    max_columns: 4
    title: Terrarium
    path: terrarium
    sections:
      - type: grid
        cards:
          - type: heading
            heading: Sensoren
            heading_style: title
          - type: history-graph
            entities:
              - entity: sensor.terrarium_temperatur_durchschnitt
            hours_to_show: 12
            grid_options:
              columns: 18
              rows: 3
          - type: history-graph
            entities:
              - entity: sensor.terrarium_luftfeuchtigkeit_durchschnitt
            hours_to_show: 12
            grid_options:
              rows: 3
              columns: 18
      - type: grid
        cards:
          - type: heading
            heading: Verhalten
            heading_style: title
          - type: tile
            entity: sensor.terrarium_zieltemperatur_aktuell
            name: Ziel Temp Aktuell
            vertical: false
            features_position: bottom
          - type: tile
            entity: sensor.terrarium_zieltemperatur_naechste
            name: Ziel Temp Naechste
            vertical: false
            features_position: bottom
          - type: tile
            entity: sensor.terrarium_heizung_naechste_aenderung
            name: Heiz Naechste Aenderung
            vertical: false
            features_position: bottom
          - type: tile
            entity: sensor.terrarium_beleuchtung_naechste_aenderung
            name: Licht Naechste Aenderung
            vertical: false
            features_position: bottom
          - type: heading
            heading: Steckdosen Status
            heading_style: subtitle
          - type: tile
            entity: binary_sensor.terrarium_lampen_aktiv
            name: Beleuchtung
            vertical: false
            features_position: bottom
          - type: tile
            entity: binary_sensor.terrarium_heizung_aktiv
            name: Heizung
            vertical: false
            features_position: bottom

  - type: sections
    max_columns: 4
    title: Frühbeet Krümel
    path: fruehbeet-kruemel
    sections:
      - type: grid
        cards:
          - type: heading
            heading: Sensoren
            heading_style: title
          - type: history-graph
            entities:
              - entity: sensor.fruhbeet_krumel_temperatur
            hours_to_show: 12
            grid_options:
              columns: 18
              rows: 3
          - type: history-graph
            entities:
              - entity: sensor.fruhbeet_krumel_luftfeuchtigkeit
            hours_to_show: 12
            grid_options:
              rows: 3
              columns: 18
      - type: grid
        cards:
          - type: heading
            heading: Verhalten
            heading_style: title
          - type: tile
            entity: sensor.fruehbeet_kruemel_zieltemperatur_aktuell
            name: Ziel Temp Aktuell
            vertical: false
            features_position: bottom
          - type: tile
            entity: sensor.fruehbeet_kruemel_zieltemperatur_naechste
            name: Ziel Temp Naechste
            vertical: false
            features_position: bottom
          - type: tile
            entity: sensor.fruehbeet_kruemel_heizung_naechste_aenderung
            name: Heiz Naechste Aenderung
            vertical: false
            features_position: bottom
          - type: tile
            entity: sensor.fruehbeet_kruemel_beleuchtung_naechste_aenderung
            name: Licht Naechste Aenderung
            vertical: false
            features_position: bottom
          - type: heading
            heading: Steckdosen Status
            heading_style: subtitle
          - type: tile
            entity: binary_sensor.fruehbeet_kruemel_lampen_aktiv
            name: Beleuchtung
            vertical: false
            features_position: bottom
          - type: tile
            entity: binary_sensor.fruehbeet_kruemel_heizung_aktiv
            name: Heizung
            vertical: false
            features_position: bottom
          - type: heading
            heading: Steckdosen Rollen
            heading_style: subtitle
          - type: tile
            entity: input_select.fruehbeet_kruemel_steckdose_links_rolle
            name: Rolle links
            vertical: false
            features_position: bottom
          - type: tile
            entity: input_select.fruehbeet_kruemel_steckdose_rechts_rolle
            name: Rolle rechts
            vertical: false
            features_position: bottom

  - type: sections
    max_columns: 4
    title: Frühbeet Sternies
    path: fruehbeet-sternies
    sections:
      - type: grid
        cards:
          - type: heading
            heading: Sensoren
            heading_style: title
          - type: history-graph
            entities:
              - entity: sensor.fruhbeet_sternies_temperatur
            hours_to_show: 12
            grid_options:
              columns: 18
              rows: 3
          - type: history-graph
            entities:
              - entity: sensor.fruhbeet_sternies_luftfeuchtigkeit
            hours_to_show: 12
            grid_options:
              rows: 3
              columns: 18
      - type: grid
        cards:
          - type: heading
            heading: Verhalten
            heading_style: title
          - type: tile
            entity: sensor.fruehbeet_sternies_zieltemperatur_aktuell
            name: Ziel Temp Aktuell
            vertical: false
            features_position: bottom
          - type: tile
            entity: sensor.fruehbeet_sternies_zieltemperatur_naechste
            name: Ziel Temp Naechste
            vertical: false
            features_position: bottom
          - type: tile
            entity: sensor.fruehbeet_sternies_heizung_naechste_aenderung
            name: Heiz Naechste Aenderung
            vertical: false
            features_position: bottom
          - type: tile
            entity: sensor.fruehbeet_sternies_beleuchtung_naechste_aenderung
            name: Licht Naechste Aenderung
            vertical: false
            features_position: bottom
          - type: heading
            heading: Steckdosen Status
            heading_style: subtitle
          - type: tile
            entity: binary_sensor.fruehbeet_sternies_lampen_aktiv
            name: Beleuchtung
            vertical: false
            features_position: bottom
          - type: tile
            entity: binary_sensor.fruehbeet_sternies_heizung_aktiv
            name: Heizung
            vertical: false
            features_position: bottom
          - type: heading
            heading: Steckdosen Rollen
            heading_style: subtitle
          - type: tile
            entity: input_select.fruehbeet_sternies_steckdose_links_rolle
            name: Rolle links
            vertical: false
            features_position: bottom
          - type: tile
            entity: input_select.fruehbeet_sternies_steckdose_rechts_rolle
            name: Rolle rechts
            vertical: false
            features_position: bottom

