views:
  - type: sections
    title: Terrarium
    path: terrarium
    max_columns: 4
    sections:
      - type: grid
        cards:
          - type: heading
            heading: Modus
            heading_style: title
          - type: tile
            entity: input_select.terrarium_lampen_modus
            name: Lampen
            vertical: false
            features_position: bottom
          - type: tile
            entity: input_select.terrarium_heizung_modus
            name: Heizung
            vertical: false
            features_position: bottom
          - type: tile
            entity: input_select.terrarium_led_modus
            name: LEDs
            vertical: false
            features_position: bottom
      - type: grid
        cards:
          - type: heading
            heading: Steckdosen Status
            heading_style: title
          - type: tile
            entity: binary_sensor.terrarium_lampen_aktiv
            name: Beleuchtung
            vertical: false
            features_position: bottom
          - type: tile
            entity: binary_sensor.terrarium_heizung_aktiv
            name: Heizung
            vertical: false
            features_position: bottom
          - type: heading
            heading: Fehler je Steckdose
            heading_style: subtitle
          - type: tile
            entity: binary_sensor.terrarium_lampen_vorne_geraete_fehler
            name: Fehler Vorne
            vertical: false
            features_position: bottom
            color: red
          - type: tile
            entity: binary_sensor.terrarium_lampen_hinten_geraete_fehler
            name: Fehler Hinten
            vertical: false
            features_position: bottom
            color: red
          - type: tile
            entity: binary_sensor.terrarium_heizung_geraete_fehler
            name: Fehler Heizung
            vertical: false
            features_position: bottom
            color: red
      - type: grid
        cards:
          - type: heading
            heading: Beleuchtung
            heading_style: title
          - type: tile
            entity: input_datetime.terrarium_lampen_start
            name: Licht An
            vertical: false
            features_position: bottom
          - type: tile
            entity: input_datetime.terrarium_lampen_ende
            name: Licht Aus
            vertical: false
            features_position: bottom
      - type: grid
        cards:
          - type: heading
            heading: Heizung
            heading_style: title
          - type: tile
            entity: input_datetime.terrarium_heizung_morgens
            name: Heiz Morgens
            vertical: false
            features_position: bottom
          - type: tile
            entity: input_datetime.terrarium_heizung_mittags
            name: Heiz Mittags
            vertical: false
            features_position: bottom
          - type: tile
            entity: input_datetime.terrarium_heizung_abends
            name: Heiz Abends
            vertical: false
            features_position: bottom
          - type: tile
            entity: input_datetime.terrarium_heizung_nachts
            name: Heiz Nachts
            vertical: false
            features_position: bottom
          - type: tile
            entity: input_number.terrarium_heizung_zieltemperatur_morgens
            name: Ziel Temp Morgens
            vertical: false
            features_position: bottom
          - type: tile
            entity: input_number.terrarium_heizung_zieltemperatur_mittags
            name: Ziel Temp Mittags
            vertical: false
            features_position: bottom
          - type: tile
            entity: input_number.terrarium_heizung_zieltemperatur_abends
            name: Ziel Temp Abends
            vertical: false
            features_position: bottom
          - type: tile
            entity: input_number.terrarium_heizung_zieltemperatur_nachts
            name: Ziel Temp Nachts
            vertical: false
            features_position: bottom
          - type: tile
            entity: input_number.terrarium_heizung_hysterese
            name: Hysterese
            vertical: false
            features_position: bottom

  - type: sections
    title: Frühbeet Krümel
    path: fruehbeet-kruemel
    max_columns: 4
    sections:
      - type: grid
        cards:
          - type: heading
            heading: Modus
            heading_style: title
          - type: tile
            entity: input_select.fruehbeet_kruemel_lampen
            name: Lampen
            vertical: false
            features_position: bottom
          - type: tile
            entity: input_select.fruehbeet_kruemel_heizung
            name: Heizung
            vertical: false
            features_position: bottom
      - type: grid
        cards:
          - type: heading
            heading: Steckdosen Rollen
            heading_style: title
          - type: tile
            entity: input_select.fruehbeet_kruemel_steckdose_links_rolle
            name: Links
            vertical: false
            features_position: bottom
          - type: tile
            entity: input_select.fruehbeet_kruemel_steckdose_rechts_rolle
            name: Rechts
            vertical: false
            features_position: bottom
      - type: grid
        cards:
          - type: heading
            heading: Steckdosen Status
            heading_style: title
          - type: tile
            entity: binary_sensor.fruehbeet_kruemel_lampen_aktiv
            name: Beleuchtung
            vertical: false
            features_position: bottom
          - type: tile
            entity: binary_sensor.fruehbeet_kruemel_heizung_aktiv
            name: Heizung
            vertical: false
            features_position: bottom
          - type: heading
            heading: Fehler je Steckdose
            heading_style: subtitle
          - type: tile
            entity: binary_sensor.fruehbeet_kruemel_links_geraete_fehler
            name: Fehler Links
            vertical: false
            features_position: bottom
            color: red
          - type: tile
            entity: binary_sensor.fruehbeet_kruemel_rechts_geraete_fehler
            name: Fehler Rechts
            vertical: false
            features_position: bottom
            color: red
      - type: grid
        cards:
          - type: heading
            heading: Beleuchtung
            heading_style: title
          - type: tile
            entity: input_datetime.fruehbeet_kruemel_lampen_start
            name: Licht An
            vertical: false
            features_position: bottom
          - type: tile
            entity: input_datetime.fruehbeet_kruemel_lampen_ende
            name: Licht Aus
            vertical: false
            features_position: bottom
      - type: grid
        cards:
          - type: heading
            heading: Heizung
            heading_style: title
          - type: tile
            entity: input_datetime.fruehbeet_kruemel_heizung_morgens
            name: Heiz Morgens
            vertical: false
            features_position: bottom
          - type: tile
            entity: input_datetime.fruehbeet_kruemel_heizung_mittags
            name: Heiz Mittags
            vertical: false
            features_position: bottom
          - type: tile
            entity: input_datetime.fruehbeet_kruemel_heizung_abends
            name: Heiz Abends
            vertical: false
            features_position: bottom
          - type: tile
            entity: input_datetime.fruehbeet_kruemel_heizung_nachts
            name: Heiz Nachts
            vertical: false
            features_position: bottom
          - type: tile
            entity: input_number.fruehbeet_kruemel_heizung_zieltemperatur_morgens
            name: Ziel Temp Morgens
            vertical: false
            features_position: bottom
          - type: tile
            entity: input_number.fruehbeet_kruemel_heizung_zieltemperatur_mittags
            name: Ziel Temp Mittags
            vertical: false
            features_position: bottom
          - type: tile
            entity: input_number.fruehbeet_kruemel_heizung_zieltemperatur_abends
            name: Ziel Temp Abends
            vertical: false
            features_position: bottom
          - type: tile
            entity: input_number.fruehbeet_kruemel_heizung_zieltemperatur_nachts
            name: Ziel Temp Nachts
            vertical: false
            features_position: bottom
          - type: tile
            entity: input_number.fruehbeet_kruemel_heizung_hysterese
            name: Hysterese
            vertical: false
            features_position: bottom

  - type: sections
    title: Frühbeet Sternies
    path: fruehbeet-sternies
    max_columns: 4
    sections:
      - type: grid
        cards:
          - type: heading
            heading: Modus
            heading_style: title
          - type: tile
            entity: input_select.fruehbeet_sternies_lampen
            name: Lampen
            vertical: false
            features_position: bottom
          - type: tile
            entity: input_select.fruehbeet_sternies_heizung
            name: Heizung
            vertical: false
            features_position: bottom
      - type: grid
        cards:
          - type: heading
            heading: Steckdosen Rollen
            heading_style: title
          - type: tile
            entity: input_select.fruehbeet_sternies_steckdose_links_rolle
            name: Links
            vertical: false
            features_position: bottom
          - type: tile
            entity: input_select.fruehbeet_sternies_steckdose_rechts_rolle
            name: Rechts
            vertical: false
            features_position: bottom
      - type: grid
        cards:
          - type: heading
            heading: Steckdosen Status
            heading_style: title
          - type: tile
            entity: binary_sensor.fruehbeet_sternies_lampen_aktiv
            name: Beleuchtung
            vertical: false
            features_position: bottom
          - type: tile
            entity: binary_sensor.fruehbeet_sternies_heizung_aktiv
            name: Heizung
            vertical: false
            features_position: bottom
          - type: heading
            heading: Fehler je Steckdose
            heading_style: subtitle
          - type: tile
            entity: binary_sensor.fruehbeet_sternies_links_geraete_fehler
            name: Fehler Links
            vertical: false
            features_position: bottom
            color: red
          - type: tile
            entity: binary_sensor.fruehbeet_sternies_rechts_geraete_fehler
            name: Fehler Rechts
            vertical: false
            features_position: bottom
            color: red
      - type: grid
        cards:
          - type: heading
            heading: Beleuchtung
            heading_style: title
          - type: tile
            entity: input_datetime.fruehbeet_sternies_lampen_start
            name: Licht An
            vertical: false
            features_position: bottom
          - type: tile
            entity: input_datetime.fruehbeet_sternies_lampen_ende
            name: Licht Aus
            vertical: false
            features_position: bottom
      - type: grid
        cards:
          - type: heading
            heading: Heizung
            heading_style: title
          - type: tile
            entity: input_datetime.fruehbeet_sternies_heizung_morgens
            name: Heiz Morgens
            vertical: false
            features_position: bottom
          - type: tile
            entity: input_datetime.fruehbeet_sternies_heizung_mittags
            name: Heiz Mittags
            vertical: false
            features_position: bottom
          - type: tile
            entity: input_datetime.fruehbeet_sternies_heizung_abends
            name: Heiz Abends
            vertical: false
            features_position: bottom
          - type: tile
            entity: input_datetime.fruehbeet_sternies_heizung_nachts
            name: Heiz Nachts
            vertical: false
            features_position: bottom
          - type: tile
            entity: input_number.fruehbeet_sternies_heizung_zieltemperatur_morgens
            name: Ziel Temp Morgens
            vertical: false
            features_position: bottom
          - type: tile
            entity: input_number.fruehbeet_sternies_heizung_zieltemperatur_mittags
            name: Ziel Temp Mittags
            vertical: false
            features_position: bottom
          - type: tile
            entity: input_number.fruehbeet_sternies_heizung_zieltemperatur_abends
            name: Ziel Temp Abends
            vertical: false
            features_position: bottom
          - type: tile
            entity: input_number.fruehbeet_sternies_heizung_zieltemperatur_nachts
            name: Ziel Temp Nachts
            vertical: false
            features_position: bottom
          - type: tile
            entity: input_number.fruehbeet_sternies_heizung_hysterese
            name: Hysterese
            vertical: false
            features_position: bottom
